import { expect, test } from "@playwright/test";

/**
 * Browser-level smoke for the golden path: visit → start a demo show
 * → live state renders → key surfaces present.
 *
 * Validates what the data-plane suite can't:
 *  - The page actually mounts (no SSR / hydration crash on '/').
 *  - The SSE handshake (POST /api/live/start → EventSource on
 *    /api/live/stream) succeeds end-to-end against the running
 *    server, not a mock.
 *  - The live show emits events that propagate into UI updates
 *    (commentary cards appear, Nemotron sees panel, etc.).
 *
 * Runs in mock-provider mode by default (NODE_ENV is unset locally,
 * so the resolver picks mock for vision/TTS). With real keys present
 * the same spec still passes because the test only asserts on
 * structural elements, not specific text generated by the model.
 */

test("home page mounts without fatal console errors and shows the discover surface", async ({ page }) => {
  const consoleErrors: string[] = [];
  page.on("console", (msg) => {
    if (msg.type() === "error") consoleErrors.push(msg.text());
  });
  await page.goto("/");
  // The discover banner's primary CTA in cold-start state.
  await expect(page.getByRole("button", { name: /try demo/i }).first()).toBeVisible({ timeout: 10_000 });
  // Filter known-noise: missing optional media assets in dev (no
  // ELEVENLABS / OPENAI keys → some upstream fetches return 4xx/5xx
  // and the browser logs a generic "Failed to load resource" line).
  // Hydration warnings from extension-injected attrs aren't ours.
  const fatal = consoleErrors.filter((line) =>
    !line.includes("Hydration") &&
    !line.toLowerCase().includes("hydration") &&
    !line.includes("401") &&
    !line.includes("403") &&
    !line.includes("404") &&
    !line.includes("500") &&
    !line.includes("favicon") &&
    !line.toLowerCase().includes("failed to load resource")
  );
  expect(fatal, `Unexpected console errors:\n${fatal.join("\n")}`).toEqual([]);
});

/**
 * Drive a demo show end-to-end. The discover banner exposes
 * "Listen to a sample" — a primary CTA that calls onPickAndStart
 * with the scripted demo game and kicks off the SSE session in one
 * click. ("Try the demo as me" opens the profile editor instead, so
 * we deliberately don't use it.)
 */
async function startDemoShow(page: import("@playwright/test").Page) {
  await page.goto("/");
  await page.getByRole("button", { name: /listen to a sample/i }).first().click();
}

test("starts a demo show and renders the live Nemotron sees panel", async ({ page }) => {
  await startDemoShow(page);
  // The "Nemotron sees" panel only mounts once a VideoObservation
  // has landed via SSE. Its presence proves the full path:
  // POST /api/live/start → EventSource on /api/live/stream → engine
  // emits observation → React updates the rail.
  await expect(page.getByText(/nemotron sees/i).first()).toBeVisible({ timeout: 30_000 });
  // Stop button only appears in live phase.
  await expect(page.getByRole("button", { name: /stop show/i }).first()).toBeVisible();
});

test("the live show exposes the Cue host push-to-talk button (W18)", async ({ page }) => {
  await startDemoShow(page);
  // The Cue host button only mounts in the audio-live phase. It's a
  // uniquely-live surface, so its presence proves the live UI tree
  // actually rendered (not just that the SSE session opened).
  await expect(page.getByRole("button", { name: /cue host/i }).first()).toBeVisible({ timeout: 30_000 });
});
